### ISSUE TITLE
Suggestions for the FAQ

### ISSUE THREAD

**Issue by frivoal** [salesforce/standards-explainers#3]
Here are a few thoughts on questions I had, which have now been answered, and you might want to incorporate in an FAQ section (maybe the "Other Solutions Considered" is that section) to benefit others with the same interrogations:

* <strong>Why not just use `::before` or `::after`?</strong>
   checkboxes are simple enough that you can create a believable one with nothing but an empty div and styling the `::before` or `::after` with generated content. However:
  * most other controls are not that simple and will need a somewhat complex anatomy that cannot be represented by `::before` and `::after` alone. Since this is part of a system, being consistent has value.
  * Changing the content of `::before` and `::after`is done through stylesheets. If/when we add a mechanism to replace the content of the indicator with something arbitrarily complicated, that won't be via the stylesheet, as that cannot create complex structures within an element. `::before` and `::after` can only contain text or images, not inlining SVGs with their full structure, so that would be limiting.
  * Inserting complex SVGs via CSS's content property is doable, but cumbersome
* <strong>What's wrong with SVG as images (as could be used in `::before` or `::after`)</strong>
   * Even if you can replace an SVG image with another SVG image that's the same thing with one attribute/property changed, that's nowhere near as convenient as being able to change a property from CSS, and you cannot animate between the two states (which you might want to do on `:hover`, or as a transition in or out of  `:checked`…)
   * SVG-as-images cannot do all the things that inline SVGs can do. It's not clear that many of these things are necessary for a checkbox, but choosing the more expressive / extensible path seems more future proof.
* <strong>Why not use U+2713 as the content of the `::indicator`?</strong> (you've answered that one already, but here's a different take)
    * While that glyph is similar in typical environments, it's font dependent, and not identical. In the case of `appearance: auto`, it's perfectly fine to have controls that vary per platform, but here were are aiming for an interoperable base as a starting point for customization. While the differences between various fonts are small on this character are small, they exist, and that's inviting trouble. An author might for example find the glyph they get to be too thin and add something to make it thicker, only to have that be inappropriate on a different OS where it was thick to start with.
    * Theoretically, CSS has lots of properties that can let you customize text to a fairly large degree, including `text-stroke` and `text-fill`, but support for them is still more shaky than the equivalent functionality in SVG.
    * As an extension point, we could introduce an additional pseudo (`::indicator-shape`?) that maps to the `path` element of the SVG, and let you adjust it. We don't yet have all the pieces in place to make that work, but it's a possible next step that isn't available if we start from a glyph, whose structure is definitely opaque. Strictly speaking, we might not need that if/when we add the possibility to replace the whole content of the `::indicator` with an alternate piece of structured markup, but (1) we haven't secured the ability to do that yet, and (2) even if we do, it could be nice to be able to tweak something in place, rather than have to replace the whole thing. Keeping the design extensible and future proof is good, even we don't end up acting on all the possible extension points. SVG offers more than text in that respect.
* <strong>How can we know we picked the right design for the SVG</strong>
    We don't expect it to be sufficient to satisfy every design, merely to be sufficiently plain and simple to broadly acceptable and easily tweakable. We do expect that more advanced usage (and possibly future trends) will call for a means to replace it, and we do intend to provide that eventually. In the meanwhile, something like what we proposed here should already cover a lot of ground. (btw, we're not locked onto the particular design showcased here, and are open to alternative suggestions, but we feel it should be something with roughly that level of complexity.)

**Comment by gregwhitworth** [comment]
love it - yeah I'll incorporate this. Thanks!!!

**Comment by gregwhitworth** [comment]
@frivoal while yeah aspects of those are covered throughout the doc I've taken most of your content and replaced it since you've done a great job clarifying key questions you and others in the CSSWG had. Very much appreciated
